#!/usr/bin/env bash
#
# Generate robots.txt for the deployed site.
#
# Why this is generated rather than checked in
# --------------------------------------------
# Its whole job is to point crawlers at the sitemaps, and the set of sitemaps
# changes every time a product releases: each MkDocs build writes its own
# sitemap.xml inside its own version directory, and nothing at the root
# references them. A hand-written robots.txt would silently stop listing new
# versions the day after it was written.
#
# What it deliberately does NOT do
# --------------------------------
# It does not block anything from being indexed. The site WANTS to be indexed.
# Duplicate content between a version and its alias copy (/riddl/2.0/ and
# /riddl/next/ are byte-identical) is already handled properly, by rel=canonical
# rather than by hiding pages: every build is built once with its version's
# site_url, so the pages inside the alias copy carry a canonical pointing at the
# real version directory. Crawlers dedupe on that and keep the right URL.
#
# Only ALIAS sitemaps are skipped, because a copied sitemap lists the version
# directory's URLs verbatim -- it is byte-identical to the one already listed,
# so advertising it adds nothing.
#
# Usage:
#   scripts/build-robots-txt.sh <site-root>
#
set -euo pipefail

ROOT="${1:?usage: build-robots-txt.sh <site-root>}"
[ -d "$ROOT" ] || { echo "no such directory: $ROOT" >&2; exit 1; }

# The canonical host. CNAME is what actually serves the site, so read it rather
# than hard-coding a second copy that can drift.
if [ -s "$ROOT/CNAME" ]; then
  HOST="https://$(tr -d '[:space:]' < "$ROOT/CNAME")"
else
  HOST="https://ossum.tech"
fi

PY="$(sed -n '1s|^#!||p' "$(command -v mkdocs)")"
[ -x "$PY" ] || PY=python3

OUT="$ROOT/robots.txt"
{
  echo "# Generated by scripts/build-robots-txt.sh -- do not edit by hand."
  echo "#"
  echo "# Everything is crawlable on purpose. Version/alias duplication is"
  echo "# resolved with rel=canonical, not by hiding pages from crawlers."
  echo
  echo "User-agent: *"
  echo "Allow: /"
  echo
  echo "# Pagefind's index: binary shards behind /find/, with no readable"
  echo "# content of their own. Crawling them wastes budget and indexes nothing."
  echo "Disallow: /pagefind/"
  echo
  echo "# One entry per real documentation build."
} > "$OUT"

# Discover sitemaps from the deployed tree, using each product's versions.json
# to tell real version directories from alias copies.
"$PY" - "$ROOT" "$HOST" >> "$OUT" <<'PY'
import json, sys
from pathlib import Path

root, host = Path(sys.argv[1]), sys.argv[2].rstrip("/")
lines = []

# The unversioned shell at the site root.
if (root / "sitemap.xml").is_file():
    lines.append(f"Sitemap: {host}/sitemap.xml")

for versions_file in sorted(root.glob("*/versions.json")):
    prefix = versions_file.parent.name
    try:
        entries = json.loads(versions_file.read_text())
    except (ValueError, OSError) as exc:
        print(f"# WARNING: could not read {prefix}/versions.json: {exc}", file=sys.stderr)
        continue
    for entry in entries:
        version = entry.get("version")
        if not version:
            continue
        # Aliases are copies whose sitemap is identical to this one, so they
        # are skipped rather than listed twice.
        if (root / prefix / version / "sitemap.xml").is_file():
            lines.append(f"Sitemap: {host}/{prefix}/{version}/sitemap.xml")

if not lines:
    print("# WARNING: no sitemaps found -- was anything deployed?", file=sys.stderr)
    sys.exit(1)

print("\n".join(lines))
PY

echo "==> Wrote $OUT"
grep -c '^Sitemap:' "$OUT" | xargs -I{} echo "    {} sitemap(s) listed"
